SELECT  * 
FROM 
  [BD_PROJECT_COVID].[dbo].[COVID_MUERTES] 
WHERE CONTINENT IS NOT NULL
ORDER BY 
  3, 4;


SELECT  * 
FROM 
  [BD_PROJECT_COVID].[dbo].[COVID_VACUNAS] 
ORDER BY 
  3, 4;


--TOTAL DE PERDIDAS EN BASE A LOS CASOS 
SELECT 
  [LOCATION], 
  [DATE], 
  [TOTAL_CASES], 
  [TOTAL_DEATHS], 
  CAST([TOTAL_DEATHS] AS FLOAT)/ [TOTAL_CASES] * 100 AS AVG_MUERTES_CASOS 
FROM 
  [BD_PROJECT_COVID]..COVID_MUERTES 
WHERE CONTINENT IS NOT NULL
ORDER BY 
  1, 2;


--TOTAL DE PERDIDAS EN BASE A LOS CASOS: PERÚ
SELECT 
  [LOCATION], 
  [DATE], 
  [TOTAL_CASES], 
  [TOTAL_DEATHS], 
  CAST([TOTAL_DEATHS] AS FLOAT)/ [TOTAL_CASES] * 100 AS AVG_MUERTES_CASOS 
FROM 
  [BD_PROJECT_COVID]..COVID_MUERTES 
WHERE 
  CONTINENT IS NOT NULL AND
  [LOCATION] LIKE 'PERU' 
ORDER BY 
  1, 2;


-- MOSTRANDO EL PORCENTAJE DE LA POBLACION QUE OBTUVO EL COVID_19
SELECT 
  [LOCATION], 
  [DATE], 
  [TOTAL_CASES],
  [POPULATION],
  CAST( TOTAL_CASES AS FLOAT)/POPULATION * 100 AS CASES_VS_POPULATION
FROM 
  [BD_PROJECT_COVID]..COVID_MUERTES
WHERE CONTINENT IS NOT NULL
ORDER BY 
  1, 2;


-- VEMOS QUE EL 13% DE LA POBLACION PERUANA FUE AFECTADA POR EL COVID-19
SELECT 
  [LOCATION], 
  [DATE], 
  [TOTAL_CASES],
  [POPULATION],
  CAST(TOTAL_CASES AS FLOAT)/POPULATION * 100 AS CASES_VS_POPULATION
FROM 
  [BD_PROJECT_COVID]..COVID_MUERTES
WHERE LOCATION LIKE 'PER%' 
AND CONTINENT IS NOT NULL
ORDER BY 
  1, 2;


-- PAISES CON TASA DE INFECCION MAS ALTA 
SELECT 
  [LOCATION],  
  MAX(
    CAST([TOTAL_CASES] AS FLOAT)
  ) AS TOTAL_CASOS, 
  MAX(
    CAST(TOTAL_CASES AS FLOAT)/ POPULATION * 100
  ) AS CASES_POPULATION 
FROM 
  [BD_PROJECT_COVID]..COVID_MUERTES 
WHERE CONTINENT IS NOT NULL
GROUP BY 
  [LOCATION] 
ORDER BY 
  CASES_POPULATION DESC;


-- PAISES CON EL MAYOR RECUENTO DE MUERTES
SELECT 
  [LOCATION], 
  MAX(
      CAST(TOTAL_DEATHS AS FLOAT)
     ) AS TOTAL_MUERTES,
  MAX(
      CAST( TOTAL_DEATHS AS FLOAT)/POPULATION * 100
      ) AS DEATHS_POPULATION
FROM 
  [BD_PROJECT_COVID]..COVID_MUERTES
WHERE CONTINENT IS NOT NULL
GROUP BY [LOCATION]
ORDER BY 
  2 DESC;


--TOTAL DE MUERTOS POR DE CADA PAIS CON SU RESPECTIVO CONTINENTE
SELECT 
  [CONTINENT],
  [LOCATION], 
  MAX(
      CAST(TOTAL_DEATHS AS FLOAT)
      ) AS TOTAL_MUERTES
FROM 
  [BD_PROJECT_COVID]..COVID_MUERTES
WHERE CONTINENT IS NOT NULL
GROUP BY [CONTINENT],[LOCATION]
ORDER BY 
  1 DESC;


--TOTAL DE MUERTOS POR CONTINENTE
SELECT 
  [LOCATION], 
  MAX(
      CAST(TOTAL_DEATHS AS FLOAT)
      ) AS TOTAL_MUERTES
FROM 
  [BD_PROJECT_COVID]..COVID_MUERTES
WHERE CONTINENT IS NULL
GROUP BY [CONTINENT], [LOCATION]
ORDER BY 
  1 DESC;


-- NUMEROS GLOBALES: VER POR FECHAS LOS CASOS EN TODO EL MUNDO
SELECT 
  [DATE], 
  SUM([NEW_CASES]) AS TotalCasosByDia, 
  SUM([NEW_DEATHS]) AS TotalMuertosByDia,
  SUM(NEW_DEATHS)/SUM([NEW_CASES]) * 100 AS PorcentajeMuertes
FROM BD_PROJECT_COVID..COVID_MUERTES
WHERE [CONTINENT] IS NOT NULL AND [NEW_CASES] != 0
GROUP BY [DATE]
ORDER BY 1;


-- NUMEROS GLOBALES: PORCENTAJE DE LA POBLACION EN TODO EL MUNDO CON COVID QUE MURIERON
SELECT  
  SUM([NEW_CASES]) AS TotalCasos_general,
  SUM([NEW_DEATHS]) as TotalMuertosB_general,
  SUM([NEW_DEATHS])/SUM([NEW_CASES]) * 100 as Porcentaje_Muertes
FROM BD_PROJECT_COVID..COVID_MUERTES
WHERE [CONTINENT] IS NOT NULL
ORDER BY 1;


-- ANALIZANDO TABLA_MUERTES CON TABLA_VACUNAS
SELECT  * 
FROM [BD_PROJECT_COVID].[dbo].[COVID_MUERTES] MT 
  JOIN [BD_PROJECT_COVID].[dbo].[COVID_VACUNAS] VC
  ON MT.location = VC.location AND MT.date = VC.date


-- MIRANDO EL TOTAL DE POBLACION QUE SE VACUNARON
SELECT  
  MT.continent, 
  MT.location, MT.date, 
  MT.population, 
  VC.new_vaccinations,
  SUM(
      CAST(VC.new_vaccinations AS FLOAT)
      ) 
    OVER (PARTITION BY MT.LOCATION ORDER BY MT.LOCATION,MT.DATE) 
    AS PERSONAS_VACUNADAS
FROM [BD_PROJECT_COVID].[dbo].[COVID_MUERTES] MT 
  JOIN [BD_PROJECT_COVID].[dbo].[COVID_VACUNAS] VC
  ON MT.location = VC.location AND MT.date = VC.date
WHERE MT.continent IS NOT NULL 
ORDER BY 2, 3;

